# Generated by Django 5.0.1 on 2024-02-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romawi', models.CharField(max_length=5)),
                ('angka', models.IntegerField()),
                ('rombel', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=50)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='DetailAbsen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.absensi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.siswa')),
            ],
        ),
    ]
