# Generated by Django 5.0.1 on 2024-02-02 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='website.kelas'),
        ),
    ]
