# Generated by Django 5.0.1 on 2024-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
