# Generated by Django 5.0.1 on 2024-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_siswa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
