# Generated by Django 5.0.1 on 2024-02-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_absensi_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto/'),
        ),
    ]
