# Generated by Django 5.0.1 on 2024-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_absensiguru_guru_detailabsenguru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailabsenguru',
            name='jam_keluar',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='detailabsenguru',
            name='jam_masuk',
            field=models.TimeField(null=True),
        ),
    ]
